#!/usr/bin/env bash
# Builds the plugin and allows you to provide a path to the vault that it should be installed in.
# Useful for when you want to dry-run the plugin in a vault other than the test vault.
PLUGIN_NAME="datacore"
VAULT="$1"

if [ -z "$VAULT" ]; then
    echo "Usage: ./scripts/install-built <path-to-your-vault-root>"
    exit 1
fi

TARGET="$VAULT/.obsidian/plugins/$PLUGIN_NAME/"

mkdir -p "$TARGET"
cp -f build/plugin/main.js build/plugin/styles.css "$TARGET"
cp -f manifest-beta.json "$TARGET/manifest.json"
echo Installed plugin "$PLUGIN_NAME" to "$TARGET"
